{% set version = "2.4.1" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: a231629d166b58b0d557fc453374374d1fe0f3aff205b34bd8196e62ec285c55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - geographiclib >=1.52

test:
  imports:
    - geopy
    - geopy.geocoders
    - geopy.extra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: Python Geocoding Toolbox.

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
